WA_ControlPresupuesto/Models/ReporteTransaccionesDetalladas.cs
namespace WA_ControlPresupuesto.Models
{
    public class ReporteTransaccionesDetalladas
    {
        public DateTime FechaInicio { get; set; }
        public DateTime FechaFin { get; set; }
        public IEnumerable<TransaccionesPorFecha> TransaccionesAgrupadas { get; set; }//Esta propiedad contendra una coleccion de objetos TransaccionesPorFecha que es una clase que definimos mas abajo
        public decimal BalanceDepositos => TransaccionesAgrupadas.Sum(t => t.BalanceDepositos);//Sumamos el balance de depositos de cada dia
        public decimal BalanceRetiros => TransaccionesAgrupadas.Sum(t => t.BalanceRetiros);//Sumamos el balance de retiros de cada dia
        //Puede confundir que abajo ya se esta sumando los depositos y retiros de cada dia, pero aqui estamos sumando el total de depositos y retiros de todo el periodo que abarca el reporte
        public decimal Total=> BalanceDepositos - BalanceRetiros;//El total es la resta de los depositos menos los retiros
        public class TransaccionesPorFecha
        {
            public DateTime FechaTransaccion { get; set; }
            public IEnumerable<Transaccion> Transacciones { get; set; }
            public decimal BalanceDepositos => 
                Transacciones.Where(t => t.TipoOperacionId == TipoOperacion.Ingreso)
                .Sum(t => t.Monto);//Lo que hace es sumar todos los ingresos de las transacciones de ese dia, si no hay ingresos devuelve 0. Estamos usando expresiones lambda, y LINQ
            public decimal BalanceRetiros => 
                Transacciones.Where(t => t.TipoOperacionId == TipoOperacion.Gasto)
                .Sum(t => t.Monto);//Aqui en lugar de ingresos, son gastos
        }
        
    }
}

WA_ControlPresupuesto/Models/ResumenMontosViewModel.cs
namespace WA_ControlPresupuesto.Models
{
    public class ResumenMontosViewModel
    {
        public decimal Ingresos { get; set; }
        public decimal Gastos { get; set; }
        public decimal Total { get; set; }
    }
}

WA_ControlPresupuesto/Controllers/CategoriasController.cs
using Microsoft.AspNetCore.Mvc;
using WA_ControlPresupuesto.Models;
using WA_ControlPresupuesto.Services;

namespace WA_ControlPresupuesto.Controllers
{
    public class CategoriasController : Controller
    {
        private readonly IRepositorioCategorias _repositorioCategorias;
        private readonly IServicioUsuarios _servicioUsuarios;

        public CategoriasController(IRepositorioCategorias repositorioCategorias, IServicioUsuarios servicioUsuarios)
        {
            _repositorioCategorias = repositorioCategorias;
            _servicioUsuarios = servicioUsuarios;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var usuarioId = _servicioUsuarios.ObtenerUsuarioId();
            var categorias = await _repositorioCategorias.Obtener(usuarioId);
            return View(categorias);
        }

        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Crear(Categoria categoria)
        {
            if (!ModelState.IsValid)//Primero validamos el modelo segun las reglas de data annotations que tenga, como required, stringlength, etc.
            {
                return View(categoria);
            }
            var usuarioId = _servicioUsuarios.ObtenerUsuarioId();
            categoria.UsuarioId = usuarioId;
            await _repositorioCategorias.Crear(categoria);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Editar(int id)//Esto es lo que aparece al entrar a la vista de editar, que es el formulario con los datos de la categoria
        {
            var usuarioId = _servicioUsuarios.ObtenerUsuarioId();
            var categoriaDB = await _repositorioCategorias.ObtenerPorId(id, usuarioId);
            if (categoriaDB is null)//Significa que la categoría no existe o no pertenece al usuario logueado.
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            return View(categoriaDB);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(Categoria categoriaEditar)//Esto es lo que aparece al hacer click en el boton de editar, que es el formulario con los datos de la categoria
        {
            if (!ModelState.IsValid)//Primero validamos el modelo segun las reglas de data annotations que tenga, como required, stringlength, etc.
            {
                return View(categoriaEditar);
            }
            var usuarioId = _servicioUsuarios.ObtenerUsuarioId();
            var categoriaDB = await _repositorioCategorias.ObtenerPorId(categoriaEditar.Id, usuarioId);
            if (categoriaDB is null)//Significa que la categoría no existe o no pertenece al usuario logueado.
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            categoriaEditar.UsuarioId = usuarioId;//Si pertenece, asignamos el usuarioId al objeto categoria que viene del formulario.
            await _repositorioCategorias.Actualizar(categoriaEditar);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Borrar(int id)
        {
            var usuarioId = _servicioUsuarios.ObtenerUsuarioId();
            var categoriaDB = await _repositorioCategorias.ObtenerPorId(id, usuarioId);
            if (categoriaDB is null)//Significa que la categoría no existe o no pertenece al usuario logueado.
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            return View(categoriaDB);
        }

        [HttpPost]
        public async Task<IActionResult> BorrarCategoria(int id)
        {
            var usuarioId = _servicioUsuarios.ObtenerUsuarioId();
            var categoriaDB = await _repositorioCategorias.ObtenerPorId(id, usuarioId);
            if (categoriaDB is null)//Significa que la categoría no existe o no pertenece al usuario logueado.
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            await _repositorioCategorias.Borrar(id);
            return RedirectToAction("Index");
        }
      
    }
}

WA_ControlPresupuesto/Controllers/CuentasController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WA_ControlPresupuesto.Models;
using WA_ControlPresupuesto.Services;

namespace WA_ControlPresupuesto.Controllers
{
    public class CuentasController : Controller
    {
        private readonly IRepositorioTiposCuentas _repositorioTiposCuentas;
        private readonly IServicioUsuarios _servicioUsuarios;
        private readonly IRepositorioCuentas _repositorioCuentas;
        private readonly IMapper _mapper;//Por convencion el name deberia ser _mapper, porque es un campo privado , pero en los ejemplos de automapper lo ponen asi, sin el _.
        private readonly IRepositorioTransacciones _repositorioTransacciones;
        private readonly IServicioReportes _servicioReportes;

        public CuentasController(IRepositorioTiposCuentas repositorioTiposCuentas, IServicioUsuarios servicioUsuarios, IRepositorioCuentas repositorioCuentas, IMapper mapper, IRepositorioTransacciones repositorioTransacciones, IServicioReportes servicioReportes)
        {
            _repositorioTiposCuentas = repositorioTiposCuentas;
            _servicioUsuarios = servicioUsuarios;
            _repositorioCuentas = repositorioCuentas;
            _mapper = mapper;//No necesitamos poner el this porque no hay ambiguedad entre el campo y el parametro del constructor
            _repositorioTransacciones = repositorioTransacciones;
            _servicioReportes = servicioReportes;
        }

        public async Task<IActionResult> Index()
        {
            var usuarioId = _servicioUsuarios.ObtenerUsuarioId();
            var cuentasConTipoCuenta = await _repositorioCuentas.Buscar(usuarioId);

            var modelo = cuentasConTipoCuenta.
                GroupBy(x => x.TipoCuenta)//Vamos a agrupar las cuentas por el TipoCuenta, por ejemplo: Ahorros, Tarjetas, etc
                .Select(grupo => new IndiceCuentasViewModel
                {
                    TipoCuenta = grupo.Key,//Es simplemente igual a TipoCuenta porque estamos agrupando por TipoCuenta
                    Cuentas = grupo.AsEnumerable()//Esto es para convertir el grupo en una enumeracion de cuentas.  Es decir, por ejempllo, que si el grupo es Ahorros, entonces Cuentas sera una enumeracion de todas las cuentas que pertenecen a Ahorros
                }).ToList();
            //En si este metodo dice: Agrupame las cuentas por TipoCuenta, y por cada grupo crea un nuevo IndiceCuentasViewModel, donde el TipoCuenta es la clave del grupo (el nombre del TipoCuenta) y las Cuentas son todas las cuentas que pertenecen a ese grupo, por ejemplo: 
            // Grupo 1: TipoCuenta = "Ahorros", Cuentas = [ { Nombre = "Cuenta Ahorros Banco1", Balance = 1500 }, { Nombre = "Cuenta Ahorros Banco2", Balance = 2500 }, { Nombre = "Cuenta Ahorros Banco3", Balance = 3000 } ]  
            // Grupo 2: TipoCuenta = "Tarjetas", Cuentas = [ { Nombre = "Tarjeta Visa", Balance = -500 }, { Nombre = "Tarjeta MasterCard", Balance = -200 } ]

            //Como balance es una propiedad calculada, no necesitamos hacer nada especial para que se calcule, ya que al acceder a la propiedad Balance, automaticamente se ejecuta el codigo que suma los balances de las cuentas
            //En si, retornamos una lista de IndiceCuentasViewModel, donde cada IndiceCuentasViewModel representa un grupo de cuentas del mismo TipoCuenta y dentro de cada IndiceCuentasViewModel tenemos la lista de cuentas que pertenecen a ese TipoCuenta 


            return View(modelo);
        }

        public async Task<IActionResult> Crear()
        {
            var usuarioId = _servicioUsuarios.ObtenerUsuarioId();
            var modelo = new CuentaCreacionViewModel();
            modelo.TiposCuentas = await ObtenerTiposCuentas(usuarioId);
            //El primer valor es el texto y el segundo es el valor. En este caso el nombre es el display y el valor a pasar es el id
            return View(modelo);
        }

        [HttpPost]
        public async Task<IActionResult> Crear(CuentaCreacionViewModel cuenta)
        {
            var usuarioId = _servicioUsuarios.ObtenerUsuarioId();
            var tipoCuenta = await _repositorioTiposCuentas.ObtenerPorId(cuenta.TipoCuentaId, usuarioId);

            if (tipoCuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            if (!ModelState.IsValid)
            {//Si el modelo no es valido, volvemos a cargar los tipos de cuentas para que el usuario pueda ver el dropdown
                cuenta.TiposCuentas = await ObtenerTiposCuentas(usuarioId);
                return View(cuenta);
            }

            await _repositorioCuentas.Crear(cuenta);
            return RedirectToAction("Index");
        }


        private async Task<IEnumerable<SelectListItem>> ObtenerTiposCuentas(int usuarioId)
        {
            var tiposCuentas = await _repositorioTiposCuentas.Obtener(usuarioId);
            return tiposCuentas.Select(x => new SelectListItem(x.Nombre, x.Id.ToString()));
        }

        public async Task<IActionResult> Editar(int id)//Solo hace la consulta de  TiposCuentas para llenar el dropdown y lo retornar a la vista y demas datos para el autollenado de cuando se este editando
        {
            var usuarioId = _servicioUsuarios.ObtenerUsuarioId();
            var cuenta = await _repositorioCuentas.ObtenerPorId(id, usuarioId);
            if (cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            var modelo = _mapper.Map<CuentaCreacionViewModel>(cuenta);//Ya con esto estoy mapeando los datos de cuenta a CuentaCreacionViewModel
            //Explicado es decir antes teniamos: 
            //var modelo = new CuentaCreacionViewModel();
            //modelo.Id = cuenta.Id;
            //modelo.Nombre = cuenta.Nombre;
            //modelo.Balance = cuenta.Balance;
            //modelo.Descripcion = cuenta.Descripcion;
            //modelo.TipoCuentaId = cuenta.TipoCuentaId;
            //Ahora con el mapper, ya no es necesario hacer  eso, porque el automapper lo hace por nosotros. Solo debemos asegurarnos que las propiedades tengan el mismo nombre en ambos modelos.
            //Y como funciona esto? Porque en Startup.cs o Program.cs, donde sea que estemos configurando los servicios, ya hemos configurado el automapper y le hemos dicho que mapee entre Cuenta y CuentaCreacionViewModel. Entonces, cuando llamamos a mapper.Map<CuentaCreacionViewModel>(cuenta), el automapper sabe que debe tomar las propiedades de cuenta y asignarlas a un nuevo objeto de tipo CuentaCreacionViewModel.
            //Es un poco dificil de entender al principio, pero es muy util cuando tenemos muchos modelos y queremos evitar escribir mucho codigo repetitivo para mapear entre ellos.
            //Un ejemplo mas claro es si tenemos un modelo de entidad que representa una tabla en la base de datos y un modelo de vista que representa los datos que queremos mostrar en la vista. Entonces, podemos usar el automapper para mapear entre estos dos modelos sin tener que escribir mucho codigo repetitivo.
            modelo.TiposCuentas = await ObtenerTiposCuentas(usuarioId);

            return View(modelo);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(CuentaCreacionViewModel cuentaEditar)
        {
            var usuarioId = _servicioUsuarios.ObtenerUsuarioId();
            var cuenta = await _repositorioCuentas.ObtenerPorId(cuentaEditar.Id, usuarioId);
            if (cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            var tipoCuenta = await _repositorioTiposCuentas.ObtenerPorId(cuentaEditar.TipoCuentaId, usuarioId);
            if (tipoCuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            if (!ModelState.IsValid)
            {
                cuentaEditar.TiposCuentas = await ObtenerTiposCuentas(usuarioId);
                return View(cuentaEditar);
            }
            await _repositorioCuentas.Actualizar(cuentaEditar);
            return RedirectToAction("Index");

        }

        [HttpGet]
        public async Task<IActionResult> Borrar(int id)
        {
            var usuarioId = _servicioUsuarios.ObtenerUsuarioId();
            var cuenta = await _repositorioCuentas.ObtenerPorId(id, usuarioId);
            if (cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            return View(cuenta);
        }

        [HttpPost]
        public async Task<IActionResult> BorrarCuenta(int id)
        {
            var usuarioId = _servicioUsuarios.ObtenerUsuarioId();
            var cuenta = await _repositorioCuentas.ObtenerPorId(id, usuarioId);
            if (cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            await _repositorioCuentas.Borrar(id);
            return RedirectToAction("Index");
        }
    
        public async Task<IActionResult> Detalle(int id, int mes, int anio)
        {
            var usuarioId = _servicioUsuarios.ObtenerUsuarioId();
            var cuenta = await _repositorioCuentas.ObtenerPorId(id, usuarioId);

            if (cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            ViewBag.Cuenta = cuenta.Nombre;

            var modelo = await _servicioReportes.ObtenerReporteTransaccionesDetalladasPorCuenta(usuarioId, id, mes, anio, ViewBag);

            return View(modelo);
        }
    }
}

WA_ControlPresupuesto/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WA_ControlPresupuesto.Models;

namespace WA_ControlPresupuesto.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly UserManager<Usuario> _userManager;

        public UsuariosController(UserManager<Usuario> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Registro()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Registro(RegistroViewModel modelo)
        {
            if(!ModelState.IsValid)
            {
                return View(modelo);
            }

            var usuario = new Usuario{Email = modelo.Email};
            var resultado = await _userManager.CreateAsync(usuario, modelo.Password);

            if(!resultado.Succeeded)
            {
                foreach(var error in resultado.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
                return View(modelo);
            }

            return RedirectToAction("Index", "Transacciones");
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

WA_ControlPresupuesto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WA_ControlPresupuesto</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WA_ControlPresupuesto.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Custom.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/lib/fullcalendar/main.min.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Transacciones" asp-action="Index">WA_ControlPresupuesto</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transacciones" asp-action="Index">Transacciones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuentas" asp-action="Index">Cuentas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TiposCuentas" asp-action="Index">Tipos Cuentas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categorias" asp-action="Index">Categorias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Registro">Usuarios</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - WA_ControlPresupuesto - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WA_ControlPresupuesto/Views/Shared/_NavegarPorMeses.cshtml
@model DateTime

<h4>
    <a asp-route-mes="@ViewBag.mesAnterior" asp-route-anio="@ViewBag.anioAnterior"
       class="btn btn-secondary"><i class="bi-chevron-left"></i></a>
    @Model.ToString("MMM")- @Model.Year
    <a asp-route-mes="@ViewBag.mesPosterior" asp-route-anio="@ViewBag.anioPosterior"
       class="btn btn-secondary"><i class="bi-chevron-right"></i></a>
</h4>

WA_ControlPresupuesto/Views/Shared/_ReporteTransaccionesDetalladas.cshtml
@model ReporteTransaccionesDetalladas
@{
    var resumenMontos = new ResumenMontosViewModel
    {
        Ingresos = Model.BalanceDepositos,
        Gastos = Model.BalanceRetiros,
        Total = Model.Total
    };
}
<partial name="_NavegarPorMeses" model="@Model.FechaInicio" />
<partial name="_ResumenMontos" model="@resumenMontos" />

@if (Model.TransaccionesAgrupadas.Count() == 0)
{
    <h5>No hay datos para mostrar</h5>
}
else
{
    <table class="table">
        <tbody>
            @foreach (var transaccionAgrupada in Model.TransaccionesAgrupadas)
            {
                <tr style="background-color: lightblue!important; font-size: 26px">
                    <td colspan="3">
                        @transaccionAgrupada.FechaTransaccion.Day
                        <span class="badge bg-success">
                            @transaccionAgrupada.FechaTransaccion.ToString("ddd")
                        </span>
                    </td>
                    <td class="activo">@transaccionAgrupada.BalanceDepositos.ToString("C")</td>
                    <td class="activo">@transaccionAgrupada.BalanceRetiros.ToString("C")</td>
                </tr>
                @foreach (var transaccion in transaccionAgrupada.Transacciones)
                {
                    <tr style="vertical-align: middle">
                        <td>
                            <a asp-controller="transacciones" asp-action="Editar"
                               asp-route-id="@transaccion.Id" asp-route-UrlRetorno="@ViewBag.UrlRetorno">
                                <i class="bi-pencil-fill"></i>
                            </a>
                        </td>
                        <td>@transaccion.Categoria</td>
                        <td>@transaccion.Cuenta</td>
                        <td class="activo">
                            @(transaccion.TipoOperacionId == TipoOperacion.Ingreso ?
                                            transaccion.Monto.ToString("C") : null)
                                                                               </td>
                                                                               <td class="pasivo">
                            @(transaccion.TipoOperacionId == TipoOperacion.Gasto ?
                                            transaccion.Monto.ToString("C") : null)
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
}

WA_ControlPresupuesto/Views/Shared/_ResumenMontos.cshtml
@model ResumenMontosViewModel

<div class="contenedor-totales  mb-3">
    <div>
        <div>
            <p class="fw-bold">Depositos</p>
        </div>
        <div class="activo">
            @Model.Ingresos.ToString("N")
            @* esa c que ponemos en el to string significa: currency, lo que hace es formatear el numero como moneda, ejemplo: $1,000.00
            ahora si ponemos la letra N esto siginifica number, lo que hace es formatear el numero como numero, ejemplo: 1,000.00*@
        </div>
    </div>
    <div>
        <div>
            <p class="fw-bold">Retiros</p>
        </div>
        <div class="pasivo">
            @Model.Gastos.ToString("C")
        </div>
    </div>
    <div>
        <div>
            <p class="fw-bold">Total</p>
        </div>
        <div>
            @Model.Total.ToString("C")
        </div>
    </div>
</div>

WA_ControlPresupuesto/Views/Shared/_Submenu.cshtml
@model SubMenuTransacciones 
<ul class="nav nav-pills nav-fill mb-3">
    <li class="nav-item">
        <a class="nav-link @(Model==SubMenuTransacciones.Diario? "active":null)" 
        asp-action="Index">Diario</a>
    </li>
    <li class="nav-item">
        <a class="nav-link @(Model==SubMenuTransacciones.Semanal? "active":null)"  
        asp-action="Semanal">Semanal</a>
    </li>
    <li class="nav-item">
        <a class="nav-link @(Model == SubMenuTransacciones.Mensual ? "active" : null)" asp-action="Mensual">Mensual</a>
    </li>
    <li class="nav-item">
        <a class="nav-link @(Model == SubMenuTransacciones.Excel ? "active" : null)" asp-action="ExcelReporte">Excel</a>
    </li>
    <li class="nav-item">
        <a class="nav-link @(Model == SubMenuTransacciones.Calendario ? "active" : null)" asp-action="Calendario">Calendario</a>
    </li>

</ul>