WA_ControlPresupuesto/Controllers/TiposCuentasController.cs
using Microsoft.AspNetCore.Mvc;
using WA_ControlPresupuesto.Models;
using WA_ControlPresupuesto.Services;

namespace WA_ControlPresupuesto.Controllers
{
    public class TiposCuentasController : Controller
    {
        private readonly IRepositorioTiposCuentas repositorioTiposCuentas;
        private readonly IServicioUsuarios servicioUsuarios;

        public TiposCuentasController(IRepositorioTiposCuentas repositorioTiposCuentas, IServicioUsuarios servicioUsuarios)
        {
            this.repositorioTiposCuentas = repositorioTiposCuentas;
            this.servicioUsuarios = servicioUsuarios;
        }

        public async Task<IActionResult> Index()
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var tiposCuentas = await repositorioTiposCuentas.Obtener(usuarioId);
            return View(tiposCuentas);
        }

        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Crear(TipoCuenta tipoCuenta)
        {//Cuando decimos task, es como si dijeramos en el futuro va a retornar tal cosa, en este caso en el futuro va a retornar IActionResult
            if (!ModelState.IsValid)
            {
                return View(tipoCuenta);
            }
            tipoCuenta.UsuarioId = servicioUsuarios.ObtenerUsuarioId();

            var yaExisteTipoCuenta = await repositorioTiposCuentas.Existe(tipoCuenta.Nombre, tipoCuenta.UsuarioId);
            if (yaExisteTipoCuenta)
            {
                ModelState.AddModelError(nameof(tipoCuenta.Nombre), $"El nombre {tipoCuenta.Nombre} ya existe");
                return View(tipoCuenta);
            }
            await repositorioTiposCuentas.Crear(tipoCuenta);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<ActionResult> Editar(int id)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var tipoCuenta = await repositorioTiposCuentas.ObtenerPorId(id, usuarioId);

            if (tipoCuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            return View(tipoCuenta);
        }


        [HttpPost]
        public async Task<ActionResult> Editar(TipoCuenta tipoCuenta)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var tipoCuentaExiste = await repositorioTiposCuentas.ObtenerPorId(tipoCuenta.Id, usuarioId);
            if (!ModelState.IsValid)
            {
                return View(tipoCuenta);
            }
            if (tipoCuentaExiste is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            await repositorioTiposCuentas.Actualizar(tipoCuenta);

            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<IActionResult> VerificarExisteTipoCuenta(string nombre)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();

            var yaExisteTipoCuenta = await repositorioTiposCuentas.Existe(nombre, usuarioId);
            if (yaExisteTipoCuenta)
            {
                return Json($"El nombre {nombre} ya existe");
            }
            return Json(true);
        }
        //Json es un formato para representar datos como una cadena de texto, sirve para llevar datos de un lugar a otro. Por ejemplo con json puedo tomar un objeto de javascript, serializarlo a json y trasmitirlo a una aplicacion de c#. Y tambien se puede hacer lo inverso, de la app de c#, serializarlo, llevarlo a JavaScript, deserealizarlo alli y acceder a sus valores


        public async Task<IActionResult> Borrar(int id)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var tipoCuenta = await repositorioTiposCuentas.ObtenerPorId(id, usuarioId);
            if (tipoCuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
                //No encontrado es la vista que hicimos en HomeController y el Home es el controlador
            }
            return View(tipoCuenta);
        }//Este metodo es usado para mostrar la vista de confirmacion de borrado, aunque parezca que no hace nada, si hace, porque busca el tipo de cuenta a borrar y si no lo encuentra redirige a la vista de no encontrado.

        [HttpPost]
        public async Task<IActionResult> BorrarTipoCuenta(int id)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var tipoCuenta = await repositorioTiposCuentas.ObtenerPorId(id, usuarioId);
            if (tipoCuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
                //No encontrado es la vista que hicimos en HomeController y el Home es el controlador
            }
            await repositorioTiposCuentas.Borrar(id);
            return RedirectToAction("Index");
        }//Este metodo es usado para hacer el borrado en si, es decir cuando se confirma el borrado


        public async Task<IActionResult> Ordenar([FromBody] int[] ids)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var tiposCuentas = await repositorioTiposCuentas.Obtener(usuarioId);

            var idsTiposCuentas = tiposCuentas.Select(x => x.Id);//Obtenemos los ids de los tipos cuentas. Lo podemos leer de la siguiente forma para no confundirnos con los x
            //Decimos "toma los tiposCuentas y por cada uno de esos tiposCuentas (a los que llamamos x) dame su Id" 

            var idsTiposCuentasNoPertenecenAlUsuario = ids.Except(idsTiposCuentas).ToList();//Verificar que los ids sean del usuario //De manera sencilla y entendible, decimos "toma los ids que me enviaste y quítales los ids que pertenecen al usuario, si queda alguno es porque no pertenece al usuario"
            //Es decir, nosotros tenemos un array de ids que nos envian desde el front, y tenemos los ids de los tipos de cuentas que pertenecen al usuario, entonces le decimos "toma los ids que me enviaste y quítales los ids que pertenecen al usuario, si queda alguno es porque no pertenece al usuario"
            //Es como si compararamos, si tenemos [1,2,3,4] y [1,2], al hacer el except quedaria [3,4], que son los que no pertenecen al usuario
            //Un ejemplo completo para ya entender este flujo desde el inicio de la funcion es el siguiente: //Supongamos que el usuario tiene los tipos de cuentas con ids [1,2,3] y desde el front nos envian los ids [2,3,4], entonces al hacer el except quedaria [4], que es el que no pertenece al usuario, por lo tanto no deberia poder ordenar ese id 4 porque no es suyo, por eso retornamos un Forbid
            //Ahora en el caso correcto, por ejemplo, el flujo seria: //Supongamos que el usuario tiene los tipos de cuentas con ids [1,2,3] y desde el front nos envian los ids [2,3,1], entonces al hacer el except quedaria [], es decir, no quedaria ninguno, porque todos los ids que nos enviaron pertenecen al usuario, por lo tanto si deberia poder ordenar esos ids. En teoria siempre debe pasar esto, porque el front deberia enviar siempre los ids correctos, pero si alguien hace una peticion maliciosa, entonces si podria enviar ids que no son del usuario, por eso hacemos esta validacion. 

            //Entonces, explicado para niños: //Tenemos los ids que el usuario tiene (1,2,3) y los ids que el usuario nos envio para ordenar (2,3,4), entonces le decimos "toma los ids que me enviaste (2,3,4) y quítales los ids que pertenecen al usuario (1,2,3), si queda alguno es porque no pertenece al usuario", en este caso quedaria (4), que es el que no pertenece al usuario, por lo tanto no deberia poder ordenar ese id 4 porque no es suyo, por eso retornamos un Forbid 

            if (idsTiposCuentasNoPertenecenAlUsuario.Count > 0)
            {
                return Forbid();//403 //Significa que no tiene permisos, prohibido
            }
            var tiposCuentasOrdenados = ids.Select((valor, indice) =>
            new TipoCuenta() { Id = valor, Orden = indice + 1 }).AsEnumerable();
            //explicado de manera sencilla y simple de entender, decimos: toma los ids que me enviaste y por cada uno de esos ids dame su valor y su indice, con eso crea un nuevo objeto de tipo TipoCuenta, asignale el id con el valor que me diste y el orden con el indice + 1 (porque el indice empieza en 0) y al final convierte todo eso en una enumeracion

            await repositorioTiposCuentas.Ordenar(tiposCuentasOrdenados);
            return Ok();
        }
    }
}

WA_ControlPresupuesto/Views/TiposCuentas/Borrar.cshtml
@model TipoCuenta
@{
    ViewData["Title"] = "Borrar Tipo de Cuenta";
}

<h3 class="mb-3">¿Está seguro que desea borrar el tipo cuenta @Model.Nombre</h3>

<form asp-action="BorrarTipoCuenta">
    <input type="hidden" asp-for="Id"/>
    <button type="submit" class="btn btn-danger">Borrar</button>
    <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
</form>

WA_ControlPresupuesto/Views/TiposCuentas/Crear.cshtml
@model TipoCuenta
@{
    ViewData["Title"] = "Crear Tipo Cuenta";
}


<h1>Crear Tipo de Cuenta</h1>
<h5>
    El tipo de cuenta se refiere a cómo podemos agrupar cuentas.
    Ejemplos: Préstamos, tarjetas de crédito, etc.
</h5>
@*All va a mostrar todos los errores, ModelOnly solo models u only*@
<div asp-validation-summary="ModelOnly" class="text-danger"></div>

<form asp-controller="TiposCuentas" asp-action="Crear">
    <div class="mb-3">
        <label asp-for="Nombre" class="form-label"></label>
        <input type="text" id="Nombre"  asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>
    @* con esto Nombre viene desde propiedades del modelo y valida sin eliminar lo que el user ya tenia escrito
 *@

   @*  Nuevas propiedades ejemplo para verificar funcionamiento de validaciones como email, edad, URL,  tarjeta de credito, etc. 
 *@
   @*  <div class="mb-3">
        <label asp-for="Email" class="form-label"></label>
        <input asp-for="Email" class="form-control" id="Email" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Edad" class="form-label"></label>
        <input asp-for="Edad" class="form-control" id="Edad" />
        <span asp-validation-for="Edad" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="URL" class="form-label"></label>
        <input asp-for="URL" class="form-control" id="URL" />
        <span asp-validation-for="URL" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="TarjetaDeCredito" class="form-label"></label>
        <input asp-for="TarjetaDeCredito" class="form-control" id="TarjetaDeCredito" />
        <span asp-validation-for="TarjetaDeCredito" class="text-danger"></span>
    </div> *@

    <button type="submit" class="btn btn-primary">Enviar</button>
    <a class="btn btn-secondary" asp-action="Index">Cancelar</a>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

WA_ControlPresupuesto/Views/TiposCuentas/Editar.cshtml
@model TipoCuenta
@{
    ViewData["Title"] = "Editar Tipo Cuenta";
}

<h1>Editar Tipo Cuenta: @Model.Nombre</h1>

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
@* asp-controller="TiposCuentas podemos especificar en el form el controller al que pertenecen, como lo hicimos en la vista crear
    pero, para estos casos (incluso en la vista crear) podiamos omitir esto, dado que estamos en la vista que pertenen a la carpeta TiposCuentas
    Es decir, es el controller
" *@
<form  asp-action="Editar">
    <input type="hidden" asp-for="Id"/>
    <div class="mb-3">
        <label asp-for="Nombre" class="form-label"></label>
        <input type="text" id="Nombre" asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Enviar</button>
    <a class="btn btn-secondary" asp-action="Index">Cancelar</a>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

WA_ControlPresupuesto/Views/TiposCuentas/Index.cshtml
@model IEnumerable<TipoCuenta>
@{
    ViewData["Title"] = "Tipos Cuentas";
}

<h1>Tipos de Cuentas</h1>
<h5>El tipo de cuenta se refiere a cómo podemos agrupar cuentas
    Ejemplos: Préstamos, tarjetas de crédito, etc.
</h5>

<a asp-action="Crear" class="btn btn-primary mb-3">Crear Nuevo</a>

<table class="table">
    <thead>
        <tr>
            <th>Acciones</th>
            <th>Nombre</th>
        </tr>
    </thead>
    <tbody id="reordenable">
        @foreach(var tipoCuenta in Model)
        {
            <tr>
                <td>
                    <input type="hidden" value="@tipoCuenta.Id" class="ids"/>
                    <a class="btn btn-primary" asp-action="Editar" asp-route-id="@tipoCuenta.Id">Editar</a>
                    <a class="btn btn-danger" asp-action="Borrar" asp-route-id="@tipoCuenta.Id">Borrar</a>
                </td>
                <td>
                    @tipoCuenta.Nombre
                </td>
            </tr>
        }
    </tbody>
</table>


@section Scripts {
    <script>
        const urlOrdenar= '@Url.Action("Ordenar")';//Genera la url para el metodo ordenar del controlador

        $(function(){
            $("#reordenable").sortable({
                stop: async function(e, ui){
                    await actualizarOrdenes();
                }
            });

            async function actualizarOrdenes(){
                const ids = ObtenerIdsDeElementos();//Este tendria el arreglo de ids
                await enviarIdsAlBackend(ids);
            }

            function ObtenerIdsDeElementos(){
                const ids = $(".ids").map(function(){
                    return $(this).val();
                }).get();
                return ids;
            }

            async function enviarIdsAlBackend(ids){
                var data = JSON.stringify(ids);
                await fetch(urlOrdenar, {
                    method: 'POST',
                    
                    body: data,
                    headers: {
                        'Content-Type': 'application/json'
                        //'Accept': 'application/json'
                    }
                })
            }
        }) 
    </script>
}