WA_ControlPresupuesto/Controllers/TransaccionesController.cs
using AutoMapper;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Data;
using System.Threading.Tasks;
using WA_ControlPresupuesto.Models;
using WA_ControlPresupuesto.Services;

namespace WA_ControlPresupuesto.Controllers
{
    public class TransaccionesController : Controller
    {
        private readonly IRepositorioTransacciones _repositorioTransacciones;
        private readonly IMapper _mapper;
        private readonly IServicioReportes servicioReportes;
        private readonly IRepositorioCuentas _repositorioCuentas;
        private readonly IRepositorioCategorias _repositorioCategorias;
        private readonly IServicioUsuarios _servicioUsuarios;
        public TransaccionesController(IServicioUsuarios servicioUsuarios, IRepositorioCuentas repositorioCuentas, IRepositorioCategorias repositorioCategorias, IRepositorioTransacciones repositorioTransacciones, IMapper mapper, IServicioReportes servicioReportes)
        {
            _servicioUsuarios = servicioUsuarios;
            _repositorioCuentas = repositorioCuentas;
            _repositorioCategorias = repositorioCategorias;
            _repositorioTransacciones = repositorioTransacciones;
            _mapper = mapper;
            this.servicioReportes = servicioReportes;
        }

        public async Task<IActionResult> Index(int mes, int anio)
        {
            var usuarioId = _servicioUsuarios.ObtenerUsuarioId();
            var modelo = await servicioReportes.ObtenerReporteTransaccionesDetalladas(usuarioId, mes, anio, ViewBag);
            return View(modelo);
        }

        public async Task<IActionResult> Semanal(int mes, int anio)
        {
            var usuarioId = _servicioUsuarios.ObtenerUsuarioId();
            IEnumerable<ResultadoObtenerPorSemana> transaccionesporSemana = await servicioReportes.ObtenerReporteSemanal(usuarioId, mes, anio, ViewBag);

            var agrupado = transaccionesporSemana.GroupBy(x => x.Semana).Select(g => new ResultadoObtenerPorSemana
            {
                Semana = g.Key,//Puede ser 1,2,3,4 o 5 dependiendo del mes
                Ingresos = g.Where(x => x.TipoOperacionId == TipoOperacion.Ingreso).
                Select(x=>x.Monto).FirstOrDefault(),//De esta forma tenemos el ingreso total de la semana
                Gastos = g.Where(x => x.TipoOperacionId == TipoOperacion.Gasto).
                Select(x=>x.Monto).FirstOrDefault(),//Tenemos el gasto total de la semana
            }).ToList();//Con esto estamos agrupando las transacciones por semana y sumando los ingresos y gastos de cada semana

            if(anio == 0 || mes == 0)
            {
                var hoy = DateTime.Today;
                anio = hoy.Year;
                mes = hoy.Month;
            }

            var fechaReferencia = new DateTime(anio, mes, 1);
            var diasDelMes = Enumerable.Range(1, fechaReferencia.AddMonths(1).AddDays(-1).Day);//Con esto obtenemos todos los dias del mes, por ejemplo, si es enero, obtenemos del 1 al 31, pero si fuese febrero, obtenemos del 1 al 28 o 29 dependiendo si es bisiesto o no

            var diasSegmentados = diasDelMes.Chunk(7).ToList();//Con esto estamos dividiendo los dias del mes en semanas, es decir, si el mes tiene 31 dias, obtenemos 5 arrays, los primeros 4 con 7 dias y el ultimo con 3 dias

            for(int i = 0; i < diasSegmentados.Count; i++)
            {
                var semana = i + 1;//La semana puede ser 1,2,3,4 o 5 dependiendo del mes
                var fechaInicio = new DateTime(anio, mes, diasSegmentados[i].First());//Obtenemos la fecha de inicio de la semana
                var fechaFin = new DateTime(anio, mes, diasSegmentados[i].Last());//Obtenemos la fecha de fin de la semana

                var grupoSemana = agrupado.FirstOrDefault(x => x.Semana == semana);
                if(grupoSemana is null)
                {
                    agrupado.Add(new ResultadoObtenerPorSemana
                    {
                        Semana = semana,
                        FechaInicio = fechaInicio,
                        FechaFin = fechaFin
                    });
                }
                else
                {//Si ya existe el grupo de la semana, solo actualizamos la fecha de inicio y fin
                    grupoSemana.FechaInicio = fechaInicio;
                    grupoSemana.FechaFin = fechaFin;
                }
            }

            agrupado = agrupado.OrderByDescending(x=>x.Semana).ToList();//Ordenamos las semanas de mayor a menor, es decir, la semana 5 primero y la semana 1 al final

            var modelo = new ReportesSemanalViewModel();
            modelo.TransaccionesPorSemana = agrupado;
            modelo.FechaReferencia = fechaReferencia;
            return View(modelo);
        }

        public async Task<IActionResult> Mensual(int anio)
        {//Poruqe es Task IActionResult y no solo IActionResult? Porque vamos a hacer una llamada asincrona
            //es decir , vamos a llamar a un metodo que devuelve una tarea, en este caso, ObtenerPorMes, que es un metodo asincrono y devuelve una tarea que contiene una lista de ResultadoObtenerPorMes
            var usuarioId = _servicioUsuarios.ObtenerUsuarioId();
            if (anio == 0)
            {
                var hoy = DateTime.Today;
                anio = hoy.Year;
            }
            var transaccionesporMes = await _repositorioTransacciones.ObtenerPorMes(usuarioId, anio);
            var transaccionesAgrupadas = transaccionesporMes.GroupBy(x=> x.Mes)
                .Select(x => new ResultadoObtenerPorMes
                {
                    Mes = x.Key,
                    Ingreso = x.Where(y => y.TipoOperacionId == TipoOperacion.Ingreso)
                                .Select(y => y.Monto).FirstOrDefault(),
                    Gasto = x.Where(y => y.TipoOperacionId == TipoOperacion.Gasto)
                                .Select(y => y.Monto).FirstOrDefault()
                }).ToList();

            for (int mes = 1; mes <= 12; mes++)
            {
                var transaccion = transaccionesAgrupadas.FirstOrDefault(x => x.Mes == mes);
                var referencia = new DateTime(anio, mes, 1);
                if (transaccion is null)
                {
                    transaccionesAgrupadas.Add(new ResultadoObtenerPorMes
                    {
                        Mes = mes,
                        FechaReferencia = referencia
                    });//Si no existe la transaccion, la agregamos con el mes y la fecha de referencia para que en la vista se muestre el mes
                }
                else
                {
                    transaccion.FechaReferencia = referencia;//Si ya existe la transaccion, solo actualizamos la fecha de referencia
                }
            }
            transaccionesAgrupadas = transaccionesAgrupadas.OrderByDescending(x => x.Mes).ToList();
            var modelo = new ReporteMensualViewModel();
            modelo.Anio = anio;
            modelo.TransaccionesPorMes = transaccionesAgrupadas;
            return View(modelo);
        }

        public IActionResult ExcelReporte()
        {
            return View();
        }

        [HttpGet]
        public async Task<FileResult> ExportarExcelPorMes(int mes, int anio)
        {
            var fechaInicio = new DateTime(anio, mes, 1);//Esto significa el primer dia del mes indicado en el parametro mes y anio
            var fechaFin = fechaInicio.AddMonths(1).AddDays(-1);//El ultimo dia del mes
            var usuarioId = _servicioUsuarios.ObtenerUsuarioId();

            var transacciones = await _repositorioTransacciones.ObtenerPorUsuarioId(
                new ParametroObtenerTransacionesPorUsuario
                {
                    UsuarioId = usuarioId,
                    FechaInicio = fechaInicio,
                    FechaFin = fechaFin
                });

            var nombreArchivo = $"ManejoPresupuesto_{fechaInicio.ToString("MMM yyyy")}.xlsx";
            return GenerarExcel(nombreArchivo, transacciones);
        }

        [HttpGet]
        public async Task<FileResult> ExportarExcelPorAnio(int anio)
        {
            var fechaInicio = new DateTime(anio, 1, 1);//Esto significa el primer dia del anio indicado en el parametro anio
            var fechaFin = fechaInicio.AddYears(1).AddDays(-1);//El ultimo dia del anio. 31 de diciembre
            var usuarioId = _servicioUsuarios.ObtenerUsuarioId();
            var transacciones = await _repositorioTransacciones.ObtenerPorUsuarioId(
                new ParametroObtenerTransacionesPorUsuario
                {
                    UsuarioId = usuarioId,
                    FechaInicio = fechaInicio,
                    FechaFin = fechaFin
                });
            var nombreArchivo = $"ManejoPresupuesto_{fechaInicio.ToString("yyyy")}.xlsx";
            return GenerarExcel(nombreArchivo, transacciones);
        }

        [HttpGet]
        public async Task<FileResult> ExportarExcelTodo()
        {
            var fechaInicio = DateTime.Today.AddYears(-100);//Hace 100 anios
            var fechaFin = DateTime.Today.AddYears(1000);//Dentro de 1000 anios

            var usuarioId = _servicioUsuarios.ObtenerUsuarioId();
            var transacciones = await _repositorioTransacciones.ObtenerPorUsuarioId(
                new ParametroObtenerTransacionesPorUsuario
                {
                    UsuarioId = usuarioId,
                    FechaInicio = fechaInicio,
                    FechaFin = fechaFin
                });
            var nombreArchivo = $"ManejoPresupuesto_Todo_{DateTime.Today.ToString("yyyy")}.xlsx";
            return GenerarExcel(nombreArchivo, transacciones);
        }

        private FileResult GenerarExcel(string nombreArchivo, IEnumerable<Transaccion> transacciones)
        {
            //Usamos la libreria ClosedXML para generar el excel

WA_ControlPresupuesto/Views/Transacciones/Calendario.cshtml
@{
    ViewBag.Title = "Reporte Calendario";
}
<partial name="_Submenu" Model="SubMenuTransacciones.Calendario" />
<div id="calendario"></div>

<div class="modal fade" id="modalTransacciones" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Transacciones del día</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th id="modalTablaFecha" colspan="2"></th>
                            <th id="modalTablaIngresos" class="activo"></th>
                            <th id="modalTablaGastos" class="pasivo"></th>
                           
                        </tr>
                    </thead>
                    <tbody id="tbodyTransaccionesModal"></tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/lib/fullcalendar/main.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const calendarEl = document.getElementById('calendario');
            const calendario = new FullCalendar.Calendar(calendarEl, {
                dayMaxEventRows: 3,
                initialView: 'dayGridMonth',
                locale: 'es',
                headerToolbar: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'dayGridMonth,timeGridWeek,timeGridDay'
                },
                events: '/Transacciones/ObtenerTransaccionesCalendario',
                dateClick: async function (info) {
                    await buscarTransaccionesPorFecha(info.dateStr);
                }

                //Ejemplo de transaccion manualmente creadaa
                // ,events: [
                //     {
                //         title: '2,500',
                //         start: '2025-09-26',
                //         end: '2025-09-26'
                //     },
                //     {
                //         title: '1, 500',
                //         start: '2025-09-25',
                //         allDay: true,
                //         color:'red'
                //     },
                //     {
                //         title: '1,300',
                //         start: '2025-09-20T10:00:00',
                //         end: '2025-09-20T12:00:00'
                //     }
                // ]
            });
            calendario.render();
        });

        async function buscarTransaccionesPorFecha(fecha){
            const response = await fetch(`/Transacciones/ObtenerTransaccionesPorFecha?fecha=${fecha}`,{
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json'
                }//Esto se hace porque el metodo GET no tiene body, entonces se pasan los parametros por la URL . Si no se hace asi, el metodo GET no recibe los parametros
                //Si no ponemos esto, el metodo GET no recibe los parametros y no funciona
                //Para entender porque si o si se debe poner te explico:
                //Cuando se hace un metodo GET, el navegador automaticamente 
                // le pone el header 'Content-Type': 'application/x-www-form-urlencoded' y no 'application/json'
                // como en los demas metodos (POST, PUT, DELETE) que si tienen body
                // y por lo tanto si tienen sentido que el Content-Type sea 'application/json', es decir que el body es un JSON
                //para definirlo mejor, en los tipo POST, PUT, DELETE se usa el Content-Type 'application/json' porque el body es un JSON
                //y en el GET no tiene body, entonces no tiene sentido que el Content-Type sea 'application/json' por eso es que el navegador le pone el header 'Content-Type': 'application/x-www-form-urlencoded'
                //y ya no estaremos enviando un body sino parametros por la URLs
                //es decir en los otros 3 se hace esto: body: content type = 'application/json' + body: JSON.stringify(objeto)
                // y en el GET no se hace body: content type = 'application/x-www-form-urlencoded' + parametros por la URL
                // y por eso es que si no ponemos el header 'Content-Type': 'application/json' en el GET, el metodo GET no recibe los parametros y no funciona
                //es decir, get no necesita body, pero si necesita el header 'Content-Type': 'application/json'
                //  para que el servidor entienda que le estamos enviando parametros por la URL

            });

            const json = await response.json();
            let ingresos = 0;
            let gastos = 0;
            const tipoOperacionesIngresos = 1;
            const formateador = new Intl.NumberFormat('es-ES', {
                style: 'currency',
                currency: 'MXN'
                //minimumFractionDigits: 2
            });

            const filas = json.map(transaccion =>{//aqui lo que estamos haciendo es mapear el json que recibimos del servidor, que es un array de transacciones, y por cada transaccion vamos a crear una fila de la tabla
                ///y ademas vamos a ir sumando los ingresos y los gastos, 
                // json.map sirve para transformar un array en otro array de la misma longitud, pero con los elementos transformados en este caso estamos transformando cada transaccion en una fila de la tabla
                if(transaccion.tipoOperacionId === tipoOperacionesIngresos){
                    ingresos += transaccion.monto;
                } else {
                    gastos += transaccion.monto;
                }
                return `<tr>
                            <td>${transaccion.categoria}</td>
                            <td>${transaccion.cuenta}</td>
                            <td align="right" colspan="2"  
                                class=${transaccion.tipoOperacionId === tipoOperacionesIngresos?
                                'activo' : 'pasivo'}>
                                ${formateador.format(transaccion.monto)}
                            </td>
                        </tr>`;
                        //lo de formateador.format lo que hace es: le da formato de moneda MXN a el monto, por ejemplo:
                        // 2500.5  lo convierte a $2,500.50. esta es una funcion de javascript, no es algo que yo haya creado, viene por defecto en javascript
            })

            $('#tbodyTransaccionesModal').html(filas);
            $('#modalTablaFecha').html(`Transacciones del día ${fecha}`);
            $('#modalTablaIngresos').html(`Ingresos: ${formateador.format(ingresos)}`);
            $('#modalTablaGastos').html(`Gastos: ${formateador.format(gastos)}`);


            const modalTransacciones = new bootstrap.Modal(document.getElementById('modalTransacciones'));
            modalTransacciones.show();
        }
    </script>
}

WA_ControlPresupuesto/Views/Transacciones/Crear.cshtml
@model TransaccionCreacionViewModel
@{
    ViewData["Title"] = "Crear Transacción";
}
<h1>@ViewData["Title"]</h1>
<h5>Una transacción te permite indicar tus ingresos y gastos</h5>

<form asp-action="Crear">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group mb-3">
        <label asp-for="FechaTransaccion" class="form-label"></label>
        <input asp-for="FechaTransaccion" class="form-control" />
        <span asp-validation-for="FechaTransaccion" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="CuentaId" class="form-label>"></label>
        <select asp-for="CuentaId" class="form-select" asp-items="Model.Cuentas"></select>
        <span asp-validation-for="CuentaId" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="TipoOperacionId" class="form-label>"></label>
        <select asp-for="TipoOperacionId" class="form-select" asp-items="Html.GetEnumSelectList<TipoOperacion>()"></select>
        <span asp-validation-for="TipoOperacionId" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="CategoriaId" class="form-label>"></label>
        <select asp-for="CategoriaId" class="form-select" asp-items="Model.Categorias"></select>
        <span asp-validation-for="CategoriaId" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="Monto" class="form-label"></label>
        <input asp-for="Monto" class="form-control" />
        <span asp-validation-for="Monto" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="Nota" class="form-label"></label>
        <textarea asp-for="Nota" class="form-control"></textarea>
        <span asp-validation-for="Nota" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Crear</button>
    <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
 @*    lo de submit es para enviar el formulario, por default si no ponemos eso es submit, es decir ya sea que especifiquemos
    que el tipo de boton es submit o no, por default lo es *@
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>
        const urlObtenerCategorias = '@Url.Action("ObtenerCategorias", "Transacciones")';
        $(function(){
            $("#TipoOperacionId").change(async function(){
                const valorSeleccionadoTipoOperacionId = $(this).val();

                const respuesta = await fetch(urlObtenerCategorias,{
                    method: 'POST',
                    body: valorSeleccionadoTipoOperacionId,
                    headers: {
                        'Content-Type': 'application/json'//
                    }
                });

                const json = await respuesta.json();
                const opciones = json.map(categoria => `<option value=${categoria.value}>${categoria.text}</option>`);
                $("#CategoriaId").html(opciones);
            })
        });
    </script>
}

WA_ControlPresupuesto/Views/Transacciones/Editar.cshtml
@model TransaccionActualizacionViewModel
@{
    ViewData["Title"] = "Editar Transacción";
    var linkCancelar = Model.UrlRetorno ?? Url.Action("Index", "Transacciones");
}
<h1>@ViewData["Title"]</h1>
<h5>Una transacción te permite indicar tus ingresos y gastos</h5>

<form asp-action="Editar">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="UrlRetorno" />
    <input type="hidden" asp-for="CuentaAnteriorId" />
    <input type="hidden" asp-for="MontoAnterior" />
    <div class="form-group mb-3">
        <label asp-for="FechaTransaccion" class="form-label"></label>
        <input asp-for="FechaTransaccion" class="form-control" />
        <span asp-validation-for="FechaTransaccion" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="CuentaId" class="form-label>"></label>
        <select asp-for="CuentaId" class="form-select" asp-items="Model.Cuentas"></select>
        <span asp-validation-for="CuentaId" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="TipoOperacionId" class="form-label>"></label>
        <select asp-for="TipoOperacionId" class="form-select" asp-items="Html.GetEnumSelectList<TipoOperacion>()"></select>
        <span asp-validation-for="TipoOperacionId" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="CategoriaId" class="form-label>"></label>
        <select asp-for="CategoriaId" class="form-select" asp-items="Model.Categorias"></select>
        <span asp-validation-for="CategoriaId" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="Monto" class="form-label"></label>
        <input asp-for="Monto" class="form-control" />
        <span asp-validation-for="Monto" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="Nota" class="form-label"></label>
        <textarea asp-for="Nota" class="form-control"></textarea>
        <span asp-validation-for="Nota" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Editar</button>
    <button type="submit" class="btn btn-danger" asp-action="Borrar">Eliminar</button>
    <a href="@linkCancelar" class="btn btn-secondary">Cancelar</a>
    @*    lo de submit es para enviar el formulario, por default si no ponemos eso es submit, es decir ya sea que especifiquemos
    que el tipo de boton es submit o no, por default lo es *@
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/FormularioTransacciones.js"></script>
    <script>
        const urlObtenerCategorias = '@Url.Action("ObtenerCategorias", "Transacciones")';
        $(function(){
            inicializarFormularioTransacciones(urlObtenerCategorias);
        });
    </script>
}

WA_ControlPresupuesto/Views/Transacciones/ExcelReporte.cshtml
@{
    ViewBag.Title = "Reporte Excel";
    var hoy = DateTime.Today;
    var haceUnMes = hoy.AddMonths(-1);
    var mesActual = hoy.Month;
    var anioActual = hoy.Year;
    var mesAnterior = haceUnMes.Month;
    var mesAnteriorAnio = haceUnMes.Year;
    var anioAnterior = anioActual - 1;
}

<partial name="_Submenu" Model="SubMenuTransacciones.Excel" />

<h1>Exportar transacciones a Excel</h1>
<div class="mb-3">
    <a asp-action="ExportarExcelPorMes" asp-route-mes="@mesActual" asp-route-anio="@anioActual"
    class="btn btn-success">
        Exportar mes actual
    </a>~@hoy.ToString("MMMM yyyy") @* lo hacemos asi porque el formato MM-yyyy es el que espera la ruta, y usamos ~ para que no tome la ruta absoluta *@
</div>

<div class="mb-3">
    <a asp-action="ExportarExcelPorMes" asp-route-mes="@mesAnterior" asp-route-anio="@mesAnteriorAnio"
    class="btn btn-success">
        Exportar mes anterior
    </a>~@haceUnMes.ToString("MMMM yyyy") @* lo hacemos asi porque el formato MM-yyyy es el que espera la ruta, y usamos ~ para que no tome la ruta absoluta *@
</div>
<div class="mb-3">
    <a asp-action="ExportarExcelPorAnio" asp-route-anio="@anioActual"
       class="btn btn-success">
        Exportar año actual
    </a>~@anioActual @* lo hacemos asi porque el formato MM-yyyy es el que espera la ruta, y usamos ~ para que no tome la ruta absoluta *@
</div>

<div class="mb-3">
    <a asp-action="ExportarExcelPorAnio" asp-route-anio="@anioAnterior"
       class="btn btn-success">
        Exportar año anterior
    </a>~@anioAnterior @* lo hacemos asi porque el formato MM-yyyy es el que espera la ruta, y usamos ~ para que no tome la ruta absoluta *@
</div>

<div class="mb-3">
    <a asp-action="ExportarExcelTodo"
       class="btn btn-success">
        Exportar todo
    </a>
</div>

WA_ControlPresupuesto/Views/Transacciones/Index.cshtml
@{
    ViewData["Title"] = "Reporte Diario";
}


<partial name="_Submenu" Model="SubMenuTransacciones.Diario" />

<a asp-action="Crear" class="btn btn-primary mb-3">Crear Nueva Transaccion</a>

<partial name="_ReporteTransaccionesDetalladas" model="Model" />

WA_ControlPresupuesto/Views/Transacciones/Mensual.cshtml
@model ReporteMensualViewModel
@{
    ViewBag.Title = "Reporte Mensual";
    int anioAnterior = Model.Anio - 1;
    int anioSiguiente = Model.Anio + 1;//Esto lo hacemos por ejemplo: si estamos en 2023, el anterior es 2022 y el siguiente es 2024

    var resumenMontos = new ResumenMontosViewModel()
            {
                Gastos = Model.Gastos,
                Ingresos = Model.Ingresos,
                Total = Model.Total
            };
}

<partial name="_Submenu" Model="SubMenuTransacciones.Mensual" />

<h4>
    Mostrando transacciones de 
    <a asp-route-anio="@anioAnterior" class="btn btn-secondary">
        <i class="bi-chevron-left"></i>
    </a>@Model.Anio
    <a asp-route-anio="@anioSiguiente" class="btn btn-secondary">
        <i class="bi-chevron-right"></i>
    </a>
</h4>

<partial name="_ResumenMontos" model="resumenMontos" />

<table class="table fs-5">
    <thead>
        <tr class="bg-light">
            <th>Mes</th>
            <th class="text-end">Ingresos</th>
            <th class="text-end">Gastos</th>
        </tr>
    </thead>
    <tbody>
        @foreach( var transaccionPorMes in Model.TransaccionesPorMes)
        {
            <tr>
                <td>
                    <a class="text-decoration-none" asp-action="Index" asp-route-anio="@Model.Anio" asp-route-mes="@transaccionPorMes.Mes">
                        @transaccionPorMes.FechaReferencia.ToString("MMM")
                    </a>
                </td>
                <td class="activo text-end"> @transaccionPorMes.Ingreso.ToString("C0")</td>
                <td class="pasivo text-end"> @transaccionPorMes.Gasto.ToString("C0")</td>
            </tr>
        }
    </tbody>
</table>

WA_ControlPresupuesto/Views/Transacciones/Semanal.cshtml
 ReportesSemanalViewModel

@{
    ViewData["Title"] = "Reporte Semanal";

    string FormatearFecha(DateTime fecha)
    {
        return fecha.ToString("MM.dd");
    }

    var resumenMontos = new ResumenMontosViewModel()
    {
        Gastos = Model.Gastos,
        Ingresos = Model.Ingresos,
        Total = Model.Total
    };
}

<partial name="_Submenu" Model="SubMenuTransacciones.Semanal" />

<partial name="_NavegarPorMeses" model="@Model.FechaReferencia" />

<partial name="_ResumenMontos" model="@resumenMontos" />

<table class="table" style=" font-size: 20px;">
    <thead>
        <tr>
            <th>Semana</th>
            <th class="text-end">Ingresos</th>
            <th class="text-end">Gastos</th>
        </tr>
    </thead>
    @foreach (var transaccionesPorSemana in Model.TransaccionesPorSemana)
    {
        <tr>
            <td>
                <a class="text-decoration-none" asp-action="Index" 
                    asp-route-anio="@Model.FechaReferencia.Year"
                    asp-route-mes="@Model.FechaReferencia.Month">
                    @FormatearFecha(transaccionesPorSemana.FechaInicio)~
                    @FormatearFecha(transaccionesPorSemana.FechaFin)
                    </a>
            </td>
            <td class="activo text-end">
                @transaccionesPorSemana.Ingresos.ToString("C0") @* El C0 es para que no muestre decimales, es decir es un formato por ejemplo: $1,000 *@
            </td>
            <td class="pasivo text-end">
                @transaccionesPorSemana.Gastos.ToString("C0") 
            </td>

        </tr>
    }
</table>